name: "Use composite action in the same repository"

on:
  push:
  workflow_dispatch:

jobs:
  greetings_with_composite_action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - run: echo "=== START ==="
      - uses: ./action.yml
      - run: echo "=== END ==="
